//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNet3dsToolkit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNet3dsToolkit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] _3DS_Builder {
            get {
                object obj = ResourceManager.GetObject("_3DS_Builder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] _3dstool {
            get {
                object obj = ResourceManager.GetObject("_3dstool", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ctrtool {
            get {
                object obj = ResourceManager.GetObject("ctrtool", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000400000007A400 12A1E1500BBC082CAED42E941B3920AE
        ///0004000000089D00 667EBE7D4194539EF895EA0E5EC20232
        ///00040000000B3900 08CA8C9B22113EE9CDAE8DFD5BAC149F
        ///00040000000E5900 54198B5BED30D5533B5353CE927EF01D
        ///00040000000F3F00 30062176B8657A412DEF628A2247C231
        ///00040000000F6B00 A81C7210AEAF377E5205CFC25A93AE31
        ///00040000000FD100 D5C770B443AB480A7DB32E0505372BDA
        ///00040000000FE600 13F88D605F595F3960FAADF938F20FDC
        ///0004000000101600 B3B356019122F2A82D27651C334D29B6
        ///0004000000101700 AE41C8B6BA6578ABDC1A64C673C1E18E
        ///00 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ext_key {
            get {
                return ResourceManager.GetString("ext_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // regex: ECMAScript grammar and case insensitive
        /////ignore:
        ///
        /////remap ignore:
        ///.
        /// </summary>
        public static string ignore_3dstool {
            get {
                return ResourceManager.GetString("ignore_3dstool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] makerom {
            get {
                object obj = ResourceManager.GetObject("makerom", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ndstool {
            get {
                object obj = ResourceManager.GetObject("ndstool", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
